# Randoms Generated by Course 
# Adding burnstat

nobo_c = read.csv("./ResSelData_Course.csv") # read in the course level data 
library(rgdal); library(raster); library(adehabitatHR); library(rgeos); library(sf); library(dplyr)
library(lubridate); library(stringr); library(hablar); library(AICcmodavg);  library(lme4); library(lwgeom)

burnmap = readOGR("E:/NOBO R Projects_Github/NOBO_ResourceSelection/Shapefiles/MasterBurnLayer__2023/Master_Burn_Plan.shp")
plot(burnmap)
summary(burnmap)

# turn nobo_i into spatial. Used for a figure below
nobo_sp <- SpatialPoints(coords = data.frame("x" = nobo_c$x, "y" = nobo_c$y)) # convert DF to Spatial Points
crs(nobo_sp) <- CRS("+init=epsg:4326") # define CRS for the spatial points (EPSG 4326 == lat/lon WGS84 etc)
nobo_sp <- spTransform(nobo_sp, crs(burnmap)) # make sure it matches OP shapefile: "North American Datum 1983" 
plot(burnmap); plot(nobo_sp, add = TRUE) # didit work? yes
extraction <- over(nobo_sp, burnmap)# extract burn status for points
nobo_c$burn_hist = extraction$Burn_Hist # Add a column to OG data file and put exracted values in
# View(nobo_c)

test <- data.frame(do.call('rbind', strsplit(as.character(nobo_c$burn_hist),',',fixed=TRUE)))

nobo_c$BurnDate1 = test$X1
nobo_c$BurnDate1 = as.Date(nobo_c$BurnDate1, "%Y-%m-%d")

nobo_c$BurnDate2 = test$X2
nobo_c$BurnDate2 = as.Date(nobo_c$BurnDate2, "%Y-%m-%d")

nobo_c = dplyr::select(nobo_c, -23) # remove the "burn_hist" containing both 
nobo_c = dplyr::select(nobo_c, -6) # removes week column 

# now to make the ifelse statement: If the date of the observation is greater
# than the BurnDate1 column then it gets a 1, if not then it gets a 0
#     TO NOTE: the BurnDate1 column contains the date of the most recent burn in 
#              a given block (which was previously extracted). Therefore, if it is
#              greater  than that given date it will be given a 1.  
nobo_c$LastBurn = with(nobo_c, ifelse(nobo_c$Date > nobo_c$BurnDate1, 1, 0))
#View(nobo_c)

# Explore the NA 
TheNA <- nobo_c %>% filter_all(any_vars(is.na(.))) # create its own little dataframe for just the NA
#View(new_data)
OP <- readOGR("E:/NOBO Project Data/Analyses/Breeding Season/Summer 2022/Adult data/Resource Use/shapefiles/OrtonCourses_JustTreatmentSites.shp")
TheNA_sp <- SpatialPoints(coords = data.frame("x" = TheNA$x, "y" = TheNA$y)) # convert NA's to Spatial Points
crs(TheNA_sp) <- CRS("+init=epsg:4326") # define CRS for the spatial points (EPSG 4326 == lat/lon WGS84 etc) 
TheNA_sp <- spTransform(TheNA_sp, crs(OP)) # make sure it matches OP shapefile: "North American Datum 1983" 
plot(OP); plot(TheNA_sp, add = TRUE, col = "blue") # notice all the points are surrounding drains or the property line ~8000 pts
head(TheNA)
# assigning them all the max number 
# this may cause issues later on, but for right now I want to keep moving. 

# Turning my focus to the ones that do have dates 
#       May just rbind the nas seperately back onto the dataframe once this piece is done 
nobo1 = subset(nobo_c, LastBurn == 1) #subset to those thats last burn date is in column BurnDate1
nobo0 = subset(nobo_c, LastBurn == 0) #subset to those thats last burn date is in column BurnDate2 
head(nobo1)

nobo1$LastBurn = nobo1$BurnDate1 #change the name for an rbind 
nobo1 = dplyr::select(nobo1, -"BurnDate2", -"BurnDate1") # delete the two columns I dont need anymore 

#repeat
nobo0$LastBurn = nobo0$BurnDate2 #change the name for an rbind 
nobo0 = dplyr::select(nobo0, -"BurnDate2", -"BurnDate1") # delete the two columns I dont need anymore 

# #combine the two back together.
nobo_c2 = rbind(nobo0, nobo1) # NOTE: this currently does not include any observations that had NA in the Burn columns 

#rbinding the NAs back into the dataframe 
# cries internnally because there was probably a more concise way of doing all this and now we are here 

head(TheNA)
TheNA = dplyr::select(TheNA, -"BurnDate2", -"BurnDate1") # delete the two columns I dont need anymore 
nobo_c2 = rbind(nobo_c2, TheNA)
nrow(nobo_c2) # check to see if its the same number as we started? YESSSS

nobo_c2$Daysinceburn = difftime(nobo_c2$Date, nobo_c2$LastBurn, units="days")
nobo_c2$Daysinceburn = round(nobo_c2$Daysinceburn, 0)
max(nobo_c2$Daysinceburn, na.rm=TRUE)
head(nobo_c2)
nobo_c2 = nobo_c2 %>% mutate(Daysinceburn = ifelse(is.na(Daysinceburn), 730, Daysinceburn)) # changing any NA in the Daysinceburn to 730 [max # of days]

#################################################################################
#################################################################################
#################################################################################

# Adding % burn to each of the points 
burn22 = raster("E:/NOBO Project Data/Analyses/Breeding Season/Summer 2023/Adult/rasters/BurnStat2022.tif")
burn23 = raster("E:/NOBO Project Data/Analyses/Breeding Season/Summer 2023/Adult/rasters/BurnStat2023.tif")

# need to subset for year and do this seperately unfortunately
nobo22 = nobo_c2[nobo_c2$Date >= "2022-01-01" & nobo_c2$Date <= "2022-12-31",]
nobo23 = nobo_c2[nobo_c2$Date >= "2023-01-01" & nobo_c2$Date <= "2023-12-31",]

nobo22_sp <- SpatialPoints(coords = data.frame("x" = nobo22$x, "y" = nobo22$y)) # convert DF to Spatial Points
nobo23_sp <- SpatialPoints(coords = data.frame("x" = nobo23$x, "y" = nobo23$y)) # convert DF to Spatial Points

crs(nobo22_sp) <- CRS("+init=epsg:4326") # define CRS for the spatial points (EPSG 4326 == lat/lon WGS84 etc)
crs(nobo23_sp) <- CRS("+init=epsg:4326") # define CRS for the spatial points (EPSG 4326 == lat/lon WGS84 etc)

nobo22_sp = spTransform(nobo22_sp, crs(burn22)) # match the crs of the necessary tiff 
nobo23_sp = spTransform(nobo23_sp, crs(burn23)) # match the crs of the necessary tiff 

plot(burn22); plot(nobo22_sp, add = TRUE) # plot 
burn22_ex <- raster::extract(x = burn22, y = nobo22_sp) # extract 
nobo22$perc_burn = burn22_ex # add column and add extracted values 

plot(burn23); plot(nobo23_sp, add = TRUE) #plot 
burn23_ex <- raster::extract(x = burn23, y = nobo23_sp) #extract 
nobo23$perc_burn = burn23_ex # add column and add extracted values 

nobo_c3 = rbind(nobo23, nobo22)

###############################################################################

# burn stat is now added. We can now proceed with the models again. 

write.csv(nobo_c3, "./ResSelData_Course2.CSV")
